window.demoSelect = function(id) {
  document.write("<select id='"+id+"'>"
    + "<option value=''>Choose a car...</option>"
    + "<option>ASTON MARTIN  DB9 COUPE</option>"
    + "<option>ASTON MARTIN  DB9 COUPE MANUAL</option>"
    + "<option>ASTON MARTIN  DB9 VOLANTE</option>"
    + "<option>ASTON MARTIN  V12 VANQUISH S</option>"
    + "<option>ASTON MARTIN  V8 VANTAGEAUDI</option>"
    + "<option>AUDI  A3</option>"
    + "<option>AUDI  A4</option>"
    + "<option>AUDI  A4 AVANT QUATTRO</option>"
    + "<option>AUDI  A4 CABRIOLET</option>"
    + "<option>AUDI  A4 CABRIOLET QUATTRO</option>"
    + "<option>AUDI  A4 QUATTRO</option>"
    + "<option>AUDI  A6</option>"
    + "<option>AUDI  A6 AVANT QUATTRO</option>"
    + "<option>AUDI  A6 QUATTRO</option>"
    + "<option>AUDI  A8 L</option>"
    + "<option>AUDI  GTI</option>"
    + "<option>AUDI  PASSAT</option>"
    + "<option>AUDI  S4</option>"
    + "<option>AUDI  S4 AVANT</option>"
    + "<option>AUDI  S4 CABRIOLET</option>"
    + "<option>AUDI  TT COUPE</option>"
    + "<option>AUDI  TT ROADSTER</option>"
    + "<option>BENTLEY MOTORS LTD. BENTLEY ARNAGE</option>"
    + "<option>BENTLEY MOTORS LTD. CONTINENTAL FLYING SPUR</option>"
    + "<option>BENTLEY MOTORS LTD. CONTINENTAL GT</option>"
    + "<option>BMW 325CI CONVERTIBLE</option>"
    + "<option>BMW 325I</option>"
    + "<option>BMW 325XI</option>"
    + "<option>BMW 325XI SPORT WAGON</option>"
    + "<option>BMW 330CI CONVERTIBLE</option>"
    + "<option>BMW 330I</option>"
    + "<option>BMW 330XI</option>"
    + "<option>BMW 525I</option>"
    + "<option>BMW 525XI</option>"
    + "<option>BMW 530I</option>"
    + "<option>BMW 530XI</option>"
    + "<option>BMW 530XI SPORT WAGON</option>"
    + "<option>BMW 550I</option>"
    + "<option>BMW 650CI</option>"
    + "<option>BMW 650CI CONVERTIBLE</option>"
    + "<option>BMW 750LI</option>"
    + "<option>BMW 760LI</option>"
    + "<option>BMW M3</option>"
    + "<option>BMW M3 CONVERTIBLE</option>"
    + "<option>BMW M5</option>"
    + "<option>BMW M6</option>"
    + "<option>BMW MINI COOPER</option>"
    + "<option>BMW MINI COOPER CONVERTIBLE</option>"
    + "<option>BMW MINI COOPER S</option>"
    + "<option>BMW MINI COOPER S CONVERTIBLE</option>"
    + "<option>BMW X3</option>"
    + "<option>BMW X5</option>"
    + "<option>BMW X5 4.8IS</option>"
    + "<option>BMW Z4 3.0 SI COUPE</option>"
    + "<option>BMW Z4 3.0I</option>"
    + "<option>BMW Z4 3.0SI</option>"
    + "<option>BMW Z4 M ROADSTER</option>"
    + "<option>Bugatti  VEYRON</option>"
    + "<option>Chrysler 300C/SRT-8</option>"
    + "<option>Chrysler CARAVAN 2WD</option>"
    + "<option>Chrysler CHARGER</option>"
    + "<option>Chrysler COMMANDER 4WD</option>"
    + "<option>Chrysler CROSSFIRE ROADSTER</option>"
    + "<option>Chrysler DAKOTA PICKUP 2WD</option>"
    + "<option>Chrysler DAKOTA PICKUP 4WD</option>"
    + "<option>Chrysler DURANGO 2WD</option>"
    + "<option>Chrysler DURANGO 4WD</option>"
    + "<option>Chrysler GRAND CHEROKEE 2WD</option>"
    + "<option>Chrysler GRAND CHEROKEE 4WD</option>"
    + "<option>Chrysler LIBERTY/CHEROKEE 2WD</option>"
    + "<option>Chrysler LIBERTY/CHEROKEE 4WD</option>"
    + "<option>Chrysler PACIFICA 2WD</option>"
    + "<option>Chrysler PACIFICA AWD</option>"
    + "<option>Chrysler PT CRUISER</option>"
    + "<option>Chrysler RAM 1500 PICKUP 2WD</option>"
    + "<option>Chrysler RAM 1500 PICKUP 4WD</option>"
    + "<option>Chrysler SEBRING 4-DR</option>"
    + "<option>Chrysler STRATUS 4-DR</option>"
    + "<option>Chrysler TOWN & COUNTRY 2WD</option>"
    + "<option>Chrysler VIPER CONVERTIBLE</option>"
    + "<option>Chrysler WRANGLER/TJ 4WD</option>"
    + "<option>FERRARI F430</option>"
    + "<option>FERRARI FERRARI 612 SCAGLIETTI</option>"
    + "<option>FERRARI FERRARI F141FORD</option>"
    + "<option>Ford  B4000 4WD</option>"
    + "<option>Ford  CROWN VICTORIA POLICE</option>"
    + "<option>Ford  E150 CLUB WAGON</option>"
    + "<option>Ford  E150 ECONOLINE 2WD</option>"
    + "<option>Ford  ESCAPE 4WD</option>"
    + "<option>Ford  ESCAPE FWD</option>"
    + "<option>Ford  ESCAPE HYBRID 4WD</option>"
    + "<option>Ford  ESCAPE HYBRID FWD</option>"
    + "<option>Ford  EXPEDITION 2WD</option>"
    + "<option>Ford  EXPLORER 2WD</option>"
    + "<option>Ford  EXPLORER 4WD</option>"
    + "<option>Ford  F150 FFV  2WD</option>"
    + "<option>Ford  F150 FFV  4WD</option>"
    + "<option>Ford  F150 PICKUP 2WD</option>"
    + "<option>Ford  F150 PICKUP 4WD</option>"
    + "<option>Ford  FIVE HUNDRED AWD</option>"
    + "<option>Ford  FIVE HUNDRED FWD</option>"
    + "<option>Ford  FOCUS  FWD</option>"
    + "<option>Ford  FOCUS STATION WAG</option>"
    + "<option>Ford  FREESTAR WAGON FWD</option>"
    + "<option>Ford  FREESTYLE AWD</option>"
    + "<option>Ford  FREESTYLE FWD</option>"
    + "<option>Ford  GRAND MARQUIS</option>"
    + "<option>Ford  GT        2WD</option>"
    + "<option>Ford  LS</option>"
    + "<option>Ford  MARK LT</option>"
    + "<option>Ford  MILAN</option>"
    + "<option>Ford  MONTEREY WAGON FWD</option>"
    + "<option>Ford  MOUNTAINEER 4WD</option>"
    + "<option>Ford  MUSTANG</option>"
    + "<option>Ford  NAVIGATOR 2WD</option>"
    + "<option>Ford  RANGER PICKUP 2WD</option>"
    + "<option>Ford  RANGER PICKUP 4WD</option>"
    + "<option>Ford  TAURUS</option>"
    + "<option>Ford  TAURUS ETHANOL FFV</option>"
    + "<option>Ford  THUNDERBIRD</option>"
    + "<option>Ford  TOWN CAR</option>"
    + "<option>Ford  ZEPHYR</option>"
    + "<option>GM  9-3 CONVERTIBLE</option>"
    + "<option>GM  9-3 SPORT SEDAN</option>"
    + "<option>GM  9-5 SEDAN</option>"
    + "<option>GM  C15 SILVERADO HYBRID 2WD</option>"
    + "<option>GM  C1500 SILVERADO 2WD</option>"
    + "<option>GM  C1500 SUBURBAN 2WD</option>"
    + "<option>GM  C1500 TAHOE 2WD</option>"
    + "<option>GM  C1500 YUKON 2WD</option>"
    + "<option>GM  COBALT</option>"
    + "<option>GM  COLORADO 2WD</option>"
    + "<option>GM  COLORADO 4WD</option>"
    + "<option>GM  COLORADO CAB CHASSIS INC 2WD</option>"
    + "<option>GM  COLORADO CREW CAB 2WD</option>"
    + "<option>GM  COLORADO CREW CAB 4WD</option>"
    + "<option>GM  CORVETTE</option>"
    + "<option>GM  CTS</option>"
    + "<option>GM  DTS</option>"
    + "<option>GM  ENVOY 2WD</option>"
    + "<option>GM  ENVOY XL 4WD</option>"
    + "<option>GM  EQUINOX AWD</option>"
    + "<option>GM  EQUINOX FWD</option>"
    + "<option>GM  ESCALADE 2WD</option>"
    + "<option>GM  ESCALADE ESV AWD</option>"
    + "<option>GM  G15/25CHEV VAN 2WD CONV</option>"
    + "<option>GM  G1500/2500 CHEVY EXPRESS 2WD</option>"
    + "<option>GM  G1500/2500 CHEVY VAN 2WD</option>"
    + "<option>GM  G6</option>"
    + "<option>GM  G6 GT/GTP CONVERTIBLE</option>"
    + "<option>GM  GRAND PRIX</option>"
    + "<option>GM  GTO</option>"
    + "<option>GM  H3 4WD</option>"
    + "<option>GM  HHR FWD</option>"
    + "<option>GM  I-280 2WD EXT CAB</option>"
    + "<option>GM  IMPALA</option>"
    + "<option>GM  K15 SILVERADO HYBRID 4WD</option>"
    + "<option>GM  K1500 AVALANCHE 4WD</option>"
    + "<option>GM  K1500 SILVERADO 4WD</option>"
    + "<option>GM  K1500 TAHOE 4WD</option>"
    + "<option>GM  LACROSSE/ALLURE</option>"
    + "<option>GM  LIMOUSINE</option>"
    + "<option>GM  MALIBU</option>"
    + "<option>GM  MONTANA SV6 AWD</option>"
    + "<option>GM  MONTE CARLO</option>"
    + "<option>GM  RENDEZVOUS AWD</option>"
    + "<option>GM  RENDEZVOUS FWD</option>"
    + "<option>GM  SOLSTICE</option>"
    + "<option>GM  SRX 2WD</option>"
    + "<option>GM  SRX AWD</option>"
    + "<option>GM  SSR PICKUP 2WD</option>"
    + "<option>GM  STS</option>"
    + "<option>GM  STS AWD</option>"
    + "<option>GM  TERRAZA FWD</option>"
    + "<option>GM  TRAILBLAZER 2WD</option>"
    + "<option>GM  TRAILBLAZER 4WD</option>"
    + "<option>GM  TRAILBLAZER AWD</option>"
    + "<option>GM  TRAILBLAZER EXT 4WD</option>"
    + "<option>GM  UPLANDER FWD</option>"
    + "<option>GM  VUE AWD</option>"
    + "<option>GM  VUE FWD</option>"
    + "<option>GM  XLR</option>"
    + "<option>Daewoo   AVEO</option>"
    + "<option>Daewoo   FORENZA</option>"
    + "<option>Daewoo   FORENZA WAGON</option>"
    + "<option>Daewoo   VERONA</option>"
    + "<option>HONDA ACCORD</option>"
    + "<option>HONDA ACCORD HYBRID</option>"
    + "<option>HONDA CIVIC</option>"
    + "<option>HONDA CIVIC HYBRID</option>"
    + "<option>HONDA CR-V 2WD</option>"
    + "<option>HONDA CR-V 4WD</option>"
    + "<option>HONDA ELEMENT 2WD</option>"
    + "<option>HONDA ELEMENT 4WD</option>"
    + "<option>HONDA INSIGHT</option>"
    + "<option>HONDA MDX 4WD</option>"
    + "<option>HONDA ODYSSEY 2WD</option>"
    + "<option>HONDA PILOT 2WD</option>"
    + "<option>HONDA PILOT 4WD</option>"
    + "<option>HONDA RIDGELINE 4WD</option>"
    + "<option>HONDA RL</option>"
    + "<option>HONDA RSX</option>"
    + "<option>HONDA S2000</option>"
    + "<option>HONDA TL</option>"
    + "<option>HONDA TSXHYUNDAI</option>"
    + "<option>HYUNDAI ACCENT</option>"
    + "<option>HYUNDAI AZERA</option>"
    + "<option>HYUNDAI ELANTRA</option>"
    + "<option>HYUNDAI SANTAFE 2WD</option>"
    + "<option>HYUNDAI SANTAFE 4WD</option>"
    + "<option>HYUNDAI SONATA</option>"
    + "<option>HYUNDAI TIBURON</option>"
    + "<option>HYUNDAI TUCSON 2WD</option>"
    + "<option>HYUNDAI TUCSON 4WDJAGUAR</option>"
    + "<option>JAGUAR S-TYPE 3.0 LITRE</option>"
    + "<option>JAGUAR S-TYPE 4.2 LITRE</option>"
    + "<option>JAGUAR S-TYPE R</option>"
    + "<option>JAGUAR VDP LWB</option>"
    + "<option>JAGUAR XJ8</option>"
    + "<option>JAGUAR XK8 CONVERTIBLE</option>"
    + "<option>JAGUAR XKR CONVERTIBLE</option>"
    + "<option>JAGUAR X-TYPE</option>"
    + "<option>JAGUAR X-TYPE SPORT BRAKEKIA</option>"
    + "<option>KIA AMANTI</option>"
    + "<option>KIA OPTIMA</option>"
    + "<option>KIA OPTIMA(MS)</option>"
    + "<option>KIA RIO</option>"
    + "<option>KIA SEDONA</option>"
    + "<option>KIA SORENTO 2WD</option>"
    + "<option>KIA SORENTO 4WD</option>"
    + "<option>KIA SPECTRA(LD)</option>"
    + "<option>KIA SPORTAGE 2WD</option>"
    + "<option>KIA SPORTAGE 4WDLAMBORGHINI</option>"
    + "<option>LAMBORGHINI L-140/715 GALLARDO</option>"
    + "<option>LAMBORGHINI L-147/148 MURCIELAGOLAND ROVER</option>"
    + "<option>LAND ROVER  LR3</option>"
    + "<option>LAND ROVER  RANGE ROVER</option>"
    + "<option>LAND ROVER  RANGE ROVER SPORT</option>"
    + "<option>LOTUS</option>"
    + "<option>LOTUS ELISE/EXIGEMASERATI</option>"
    + "<option>MASERATI  COUPE CAMBIOCORSA/GT/G-SPORT</option>"
    + "<option>MASERATI QUATTROPORTEMAZDZ</option>"
    + "<option>MAZDA 3</option>"
    + "<option>MAZDA 5</option>"
    + "<option>MAZDA 6</option>"
    + "<option>MAZDA 6 SPORT WAGON</option>"
    + "<option>MAZDA RX-8</option>"
    + "<option>MERCEDES BENZ C230</option>"
    + "<option>MERCEDES BENZ C280</option>"
    + "<option>MERCEDES BENZ C280 4MATIC</option>"
    + "<option>MERCEDES BENZ C350</option>"
    + "<option>MERCEDES BENZ C350 4MATIC</option>"
    + "<option>MERCEDES BENZ C55 AMG</option>"
    + "<option>MERCEDES BENZ CL65 AMG</option>"
    + "<option>MERCEDES BENZ CLK350</option>"
    + "<option>MERCEDES BENZ CLK350 (CABRIOLET)</option>"
    + "<option>MERCEDES BENZ CLK55 AMG (CABRIOLET)</option>"
    + "<option>MERCEDES BENZ CLS500</option>"
    + "<option>MERCEDES BENZ CLS55 AMG</option>"
    + "<option>MERCEDES BENZ E320 CDI</option>"
    + "<option>MERCEDES BENZ E350</option>"
    + "<option>MERCEDES BENZ E350 (WAGON)</option>"
    + "<option>MERCEDES BENZ E350 4MATIC</option>"
    + "<option>MERCEDES BENZ E350 4MATIC (WAGON)</option>"
    + "<option>MERCEDES BENZ E500</option>"
    + "<option>MERCEDES BENZ E55 AMG</option>"
    + "<option>MERCEDES BENZ E55 AMG (WAGON)</option>"
    + "<option>MERCEDES BENZ MAYBACH 57S</option>"
    + "<option>MERCEDES BENZ MAYBACH 62</option>"
    + "<option>MERCEDES BENZ ML350</option>"
    + "<option>MERCEDES BENZ ML500</option>"
    + "<option>MERCEDES BENZ R350</option>"
    + "<option>MERCEDES BENZ R500</option>"
    + "<option>MERCEDES BENZ S350</option>"
    + "<option>MERCEDES BENZ S430</option>"
    + "<option>MERCEDES BENZ SL500</option>"
    + "<option>MERCEDES BENZ SL600</option>"
    + "<option>MERCEDES BENZ SL65 AMG</option>"
    + "<option>MERCEDES BENZ SLK280</option>"
    + "<option>MERCEDES BENZ SLK350</option>"
    + "<option>MERCEDES BENZ SLR</option>"
    + "<option>Mitsubishi  ECLIPSE</option>"
    + "<option>Mitsubishi  ENDEAVOR 2WD</option>"
    + "<option>Mitsubishi  ENDEAVOR 4WD</option>"
    + "<option>Mitsubishi  GALANT</option>"
    + "<option>Mitsubishi  LANCER</option>"
    + "<option>Mitsubishi  LANCER EVOLUTION</option>"
    + "<option>Mitsubishi  LANCER SPORTBACK</option>"
    + "<option>Mitsubishi  MONTERO</option>"
    + "<option>Mitsubishi  OUTLANDER 2WD</option>"
    + "<option>Mitsubishi  OUTLANDER 4WD</option>"
    + "<option>Nissan  350Z</option>"
    + "<option>Nissan  350Z ROADSTER</option>"
    + "<option>Nissan  ALTIMA</option>"
    + "<option>Nissan  ARMADA 2WD</option>"
    + "<option>Nissan  ARMADA 4WD</option>"
    + "<option>Nissan  FRONTIER 2WD</option>"
    + "<option>Nissan  FRONTIER V6-2WD</option>"
    + "<option>Nissan  FRONTIER V6-4WD</option>"
    + "<option>Nissan  FX35 AWD</option>"
    + "<option>Nissan  FX35 RWD</option>"
    + "<option>Nissan  FX45 AWD</option>"
    + "<option>Nissan  G35</option>"
    + "<option>Nissan  M35</option>"
    + "<option>Nissan  M35X</option>"
    + "<option>Nissan  M45</option>"
    + "<option>Nissan  MAXIMA</option>"
    + "<option>Nissan  MURANO AWD</option>"
    + "<option>Nissan  MURANO FWD</option>"
    + "<option>Nissan  PATHFINDER 2WD</option>"
    + "<option>Nissan  PATHFINDER 4WD</option>"
    + "<option>Nissan  Q45</option>"
    + "<option>Nissan  Q45 SPORT</option>"
    + "<option>Nissan  QUEST</option>"
    + "<option>Nissan  QX56 4WD</option>"
    + "<option>Nissan  SENTRA</option>"
    + "<option>Nissan  TITAN 2WD</option>"
    + "<option>Nissan  TITAN 4WD</option>"
    + "<option>Nissan  XTERRA 2WD</option>"
    + "<option>Nissan  XTERRA 4WDPORSCHE</option>"
    + "<option>PORSCHE BOXSTER</option>"
    + "<option>PORSCHE BOXSTER S</option>"
    + "<option>PORSCHE CARRERA 2 COUPE</option>"
    + "<option>PORSCHE CAYENNE</option>"
    + "<option>PORSCHE CAYENNE S</option>"
    + "<option>PORSCHE CAYENNE TURBO</option>"
    + "<option>PORSCHE CAYMAN S</option>"
    + "<option>Rolls-Royce   PHANTOMROUSH</option>"
    + "<option>SUZUKI  AERIO</option>"
    + "<option>SUZUKI  AERIO SX</option>"
    + "<option>SUZUKI  AERIO SX AWD</option>"
    + "<option>SUZUKI  GRAND VITARA XL-7</option>"
    + "<option>SUZUKI  GRAND VITARA XL-7 4WD</option>"
    + "<option>SUZUKI  GRAND VITARA XV6</option>"
    + "<option>SUZUKI  GRAND VITARA XV6 AWD</option>"
    + "<option>TOYOTA  4RUNNER 2WD</option>"
    + "<option>TOYOTA  4RUNNER 4WD</option>"
    + "<option>TOYOTA  AVALON</option>"
    + "<option>TOYOTA  CAMRY</option>"
    + "<option>TOYOTA  CAMRY SOLARA</option>"
    + "<option>TOYOTA  CAMRY SOLARA CONVERTIBLE</option>"
    + "<option>TOYOTA  COROLLA</option>"
    + "<option>TOYOTA  COROLLA MATRIX</option>"
    + "<option>TOYOTA  ES 330</option>"
    + "<option>TOYOTA  GS 300 4WD</option>"
    + "<option>TOYOTA  GS 300/GS 430</option>"
    + "<option>TOYOTA  GX 470</option>"
    + "<option>TOYOTA  HIGHLANDER 2WD</option>"
    + "<option>TOYOTA  HIGHLANDER 4WD</option>"
    + "<option>TOYOTA  HIGHLANDER HYBRID 2WD</option>"
    + "<option>TOYOTA  HIGHLANDER HYBRID 4WD</option>"
    + "<option>TOYOTA  IS 250</option>"
    + "<option>TOYOTA  IS 250 AWD</option>"
    + "<option>TOYOTA  IS 350</option>"
    + "<option>TOYOTA  LS 430</option>"
    + "<option>TOYOTA  LX 470</option>"
    + "<option>TOYOTA  PRIUS</option>"
    + "<option>TOYOTA  RAV4 2WD</option>"
    + "<option>TOYOTA  RAV4 4WD</option>"
    + "<option>TOYOTA  RX 330 2WD</option>"
    + "<option>TOYOTA  RX 330 4WD</option>"
    + "<option>TOYOTA  RX 400H 4WD</option>"
    + "<option>TOYOTA  SC 430</option>"
    + "<option>TOYOTA  SCION TC</option>"
    + "<option>TOYOTA  SCION XA</option>"
    + "<option>TOYOTA  SCION XB</option>"
    + "<option>TOYOTA  SEQUOIA 2WD</option>"
    + "<option>TOYOTA  SEQUOIA 4WD</option>"
    + "<option>TOYOTA  SIENNA 2WD</option>"
    + "<option>TOYOTA  SIENNA 4WD</option>"
    + "<option>TOYOTA  TOYOTA TACOMA 2WD</option>"
    + "<option>TOYOTA  TOYOTA TACOMA 4WD</option>"
    + "<option>TOYOTA  TOYOTA TUNDRA 2WD</option>"
    + "<option>TOYOTA  TOYOTA TUNDRA 4WD</option>"
    + "<option>TOYOTA  YARIS</option>"
    + "<option>VOLKSWAGEN  A3 QUATTRO</option>"
    + "<option>VOLKSWAGEN  GOLF</option>"
    + "<option>VOLKSWAGEN  JETTA</option>"
    + "<option>VOLKSWAGEN  NEW BEETLE</option>"
    + "<option>VOLKSWAGEN  NEW BEETLE CONVERTIBLE</option>"
    + "<option>VOLKSWAGEN  PASSAT WAGON 4MOTION</option>"
    + "<option>VOLKSWAGEN  PHAETON</option>"
    + "<option>VOLKSWAGEN  RABBIT</option>"
    + "<option>VOLKSWAGEN  TOUAREG</option>"
    + "<option>VOLKSWAGEN  TT COUPE QUATTRO</option>"
    + "<option>VOLKSWAGEN  TT ROADSTER QUATTRO</option>"
    + "<option>VOLVO NEW C70 CONVERTIBLE</option>"
    + "<option>VOLVO S40 AWD</option>"
    + "<option>VOLVO S40 FWD</option>"
    + "<option>VOLVO S60 AWD</option>"
    + "<option>VOLVO S60 FWD</option>"
    + "<option>VOLVO S60 R AWD</option>"
    + "<option>VOLVO S80 FWD</option>"
    + "<option>VOLVO V50 AWD</option>"
    + "<option>VOLVO V70 FWD</option>"
    + "<option>VOLVO V70 R AWD</option>"
    + "<option>VOLVO XC 70 AWD</option>"
    + "<option>VOLVO XC 90 AWD</option>"
    + "<option>VOLVO XC 90 FWD</option>"
    + "</select>"
  )
  return $('#'+id)
}